[package]
name = "argus-gitpulse"
version.workspace = true
edition.workspace = true

[dependencies]
argus-core = { workspace = true }
git2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
